apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teaching-web
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sqora-app
                port:
                  name: backend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teaching-tts
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /tts(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: headtts
                port:
                  name: http
